// AUTO-GENERATED by tools/build_official_map.mjs — do not edit by hand.
// Re-run `npm run sync:map` after re-exporting the map from games/map.
import type { Rect, Vec2 } from "./map.js";

/** Walkable land: AABB footprints of every floor/platform mesh (island slabs
 *  + connecting paths). Water is any point inside none of these. */
export const FLOOR_RECTS: readonly Rect[] = [{"minX":-38.09,"maxX":21,"minZ":-21,"maxZ":21},{"minX":-43.05,"maxX":-28.39,"minZ":44.8,"maxZ":59.08},{"minX":-17.64,"maxX":8.41,"minZ":57.38,"maxZ":78.35},{"minX":-6.05,"maxX":2.7,"minZ":54.9,"maxZ":63.33},{"minX":-80,"maxX":21,"minZ":46.02,"maxZ":131},{"minX":-6,"maxX":6,"minZ":20.99,"maxZ":45.99},{"minX":20.5,"maxX":45.5,"minZ":46,"maxZ":58},{"minX":20.5,"maxX":45.5,"minZ":-2,"maxZ":10},{"minX":44,"maxX":143,"minZ":-9,"maxZ":119},{"minX":-35,"maxX":122.03,"minZ":-224.6,"maxZ":-45.8},{"minX":51.73,"maxX":57.49,"minZ":-116.97,"maxZ":-111.21},{"minX":-1,"maxX":11,"minZ":-45.99,"maxZ":-20.99},{"minX":55,"maxX":67,"minZ":-45.99,"maxZ":-8.98}];

/** Authored scene markers (spawn, zones, bosses, node anchors, stall). */
export const MAP_MARKERS: Readonly<Record<string, Vec2>> = {"Spawn_Town":{"x":3.69,"z":-3.67},"Zone_Area1":{"x":-25.7,"z":81.2},"Node_Crystal_01":{"x":-30.3,"z":60.1},"Node_Fish_01":{"x":-9.9,"z":29.6},"Boss_Area1":{"x":-56.7,"z":102},"Zone_Area2":{"x":88.9,"z":50.4},"Boss_Area2":{"x":122.4,"z":36.7},"Zone_Area3":{"x":49.2,"z":-63.2},"Boss_Area3":{"x":66.4,"z":-126.7},"Coliseum_Center":{"x":73.6,"z":-180.4},"Node_Iron_01":{"x":-17.5,"z":-118.9},"Stall_Market":{"x":-34.3,"z":9.86}};
