// Distil the raw Unity map export into a compact, typed TS module the shared
// @depthbreaker/protocol package imports. Re-run after every map re-export:
//   npm run sync:map
//
// Emits packages/protocol/src/officialMapData.ts with:
//   WALK_GRID   — per-cell walkability (raycast; only real blocks) + surface
//                 height, base64-packed (bitmask + uint8 height *4). Water/lava/
//                 gaps are excluded, and the player follows ramps/reliefs.
//   BOUND_RECTS — the floor-slab AABBs, used only for map bounds (minimap /
//                 click-plane sizing), NOT for walkability.
//   MAP_MARKERS — authored empties (Spawn/Zone/Boss/Node/Stall).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const mapDir = resolve(root, "client/public/models/map");
const layout = JSON.parse(readFileSync(resolve(mapDir, "map1_layout.json"), "utf8"));
const grid = JSON.parse(readFileSync(resolve(mapDir, "map1_grid.json"), "utf8"));

// --- Bounding rects (floor slabs) — for map extent only ---
const isFloor = (name) => /Floor|Floo\b|Rock_Platform/i.test(name) && !/wall|door|cliff|lava/i.test(name);
const boundRects = layout.meshes
  .filter((m) => isFloor(m.name))
  .map((m) => ({
    minX: +(m.cx - m.sx / 2).toFixed(2),
    maxX: +(m.cx + m.sx / 2).toFixed(2),
    minZ: +(m.cz - m.sz / 2).toFixed(2),
    maxZ: +(m.cz + m.sz / 2).toFixed(2),
  }));

// --- Markers ---
const markers = {};
for (const mk of layout.markers) {
  if (/light|camera/i.test(mk.name)) continue;
  markers[mk.name] = { x: +mk.x.toFixed(2), z: +mk.z.toFixed(2) };
}

// --- Walkability + height grid → packed base64 ---
const cols = grid.cols, rows = grid.rows, n = cols * rows;
const walkStr = grid.walk;
const heightArr = grid.height.split(","); // "_" for non-walkable cells
const HEIGHT_Q = 4; // 0.25u resolution
// Walk bitmask: 1 bit per cell.
const bits = new Uint8Array(Math.ceil(n / 8));
// Height: uint8 = round(h * HEIGHT_Q), clamped. Non-walkable cells store 0.
const hbytes = new Uint8Array(n);
let walkCount = 0;
for (let i = 0; i < n; i++) {
  if (walkStr[i] === "1") {
    bits[i >> 3] |= 1 << (i & 7);
    const h = parseFloat(heightArr[i]);
    hbytes[i] = Math.max(0, Math.min(255, Math.round((Number.isFinite(h) ? h : 0) * HEIGHT_Q)));
    walkCount++;
  }
}
const b64 = (u8) => Buffer.from(u8).toString("base64");

const out = `// AUTO-GENERATED by tools/build_official_map.mjs — do not edit by hand.
// Re-run \`npm run sync:map\` after re-exporting the map from games/map.
import type { Rect, Vec2 } from "./map.js";

/** Floor-slab AABBs — used only to compute the map's extent (minimap / click
 *  plane). Walkability comes from WALK_GRID, not these. */
export const BOUND_RECTS: readonly Rect[] = ${JSON.stringify(boundRects)};

/** Authored scene markers (spawn, zones, bosses, node anchors, stall). */
export const MAP_MARKERS: Readonly<Record<string, Vec2>> = ${JSON.stringify(markers)};

/** Raycast walkability + surface height. \`bits\` is a 1-bit-per-cell walkable
 *  mask; \`height\` is uint8 = surfaceY * ${HEIGHT_Q} (0.25u steps) per walkable
 *  cell. Cell (gx,gz) → index gz*cols+gx; world x = originX + gx*cell. */
export const WALK_GRID = {
  originX: ${grid.originX},
  originZ: ${grid.originZ},
  cell: ${grid.cell},
  cols: ${cols},
  rows: ${rows},
  heightQ: ${HEIGHT_Q},
  bits: "${b64(bits)}",
  height: "${b64(hbytes)}",
} as const;
`;

writeFileSync(resolve(root, "packages/protocol/src/officialMapData.ts"), out);
console.log(`officialMapData.ts: ${boundRects.length} bound rects, ${Object.keys(markers).length} markers, grid ${cols}x${rows} (${walkCount} walkable)`);
