// Distil the raw Unity map export (client/public/models/map/map1_layout.json)
// into a compact, typed TS module the shared @depthbreaker/protocol package
// imports (no resolveJsonModule needed, tiny bundle). Re-run after every map
// re-export:  npm run sync:map
//
// Emits packages/protocol/src/officialMapData.ts with:
//   FLOOR_RECTS  — walkable land = AABB footprints of floor/platform meshes
//   MAP_MARKERS  — every author empty (Spawn_Town, Zone_/Boss_/Node_, Stall_…)

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const layout = JSON.parse(readFileSync(resolve(root, "client/public/models/map/map1_layout.json"), "utf8"));

// Walkable = floor slabs, path floors, grass rock-platforms. Everything else
// (walls, props, lava, cliffs, water) is NOT land.
const isFloor = (name) => /Floor|Floo\b|Rock_Platform/i.test(name) && !/wall|door|cliff|lava/i.test(name);

const rects = layout.meshes
  .filter((m) => isFloor(m.name))
  .map((m) => ({
    minX: +(m.cx - m.sx / 2).toFixed(2),
    maxX: +(m.cx + m.sx / 2).toFixed(2),
    minZ: +(m.cz - m.sz / 2).toFixed(2),
    maxZ: +(m.cz + m.sz / 2).toFixed(2),
  }));

// Markers: drop Unity's Light/Camera; keep authored empties by name.
const markers = {};
for (const mk of layout.markers) {
  if (/light|camera/i.test(mk.name)) continue;
  markers[mk.name] = { x: +mk.x.toFixed(2), z: +mk.z.toFixed(2) };
}

const out = `// AUTO-GENERATED by tools/build_official_map.mjs — do not edit by hand.
// Re-run \`npm run sync:map\` after re-exporting the map from games/map.
import type { Rect, Vec2 } from "./map.js";

/** Walkable land: AABB footprints of every floor/platform mesh (island slabs
 *  + connecting paths). Water is any point inside none of these. */
export const FLOOR_RECTS: readonly Rect[] = ${JSON.stringify(rects)};

/** Authored scene markers (spawn, zones, bosses, node anchors, stall). */
export const MAP_MARKERS: Readonly<Record<string, Vec2>> = ${JSON.stringify(markers)};
`;

writeFileSync(resolve(root, "packages/protocol/src/officialMapData.ts"), out);
console.log(`officialMapData.ts: ${rects.length} floor rects, ${Object.keys(markers).length} markers`);
